### ISSUE TITLE
Using local images

### ISSUE THREAD

**Issue by dentonsavage** [stormlion227/PhotoBrowser.Forms#1]
How can I use local images? 

Code snippet:
new Photo
{
   URL = "music.jpg",
   Title = "Korben"
},

**Comment by stormlion227** [comment]
I'll add the feature in few days.

**Comment by soile1991** [comment]
You can let us load an image from stream or byte array to be able to load saved on device storage / cache.

**Comment by dentonsavage** [comment]
I updated the code as follows and it works.

Code snippet:
new Photo
{
URL = "file:///user/images/music.jpg",
Title = "Korben"
},

and that works.
***********************************
How can I use local images?

Code snippet:
new Photo
{
URL = "music.jpg",
Title = "Korben"
},

**Comment by armaganX** [comment]
thank you @dentonsavage
