### ISSUE TITLE
Compability with Rg.Plugins.Popup

### ISSUE THREAD

**Issue by nathan1658** [stormlion227/PhotoBrowser.Forms#21]
Hello, the plugin is excellent and my app do enjoy the convenience on all your hard effort.
This issue might be out of the scope, however I found that if I try to view the PhotoBrowser inside the pop up screen, nothing happened on iOS but works on android. I'm beginner of iOS developer but i suspect there might be something related to the code below in MyMWPhotoBrowser:
`  UIApplication.SharedApplication.KeyWindow.RootViewController.PresentViewController(new UINavigationController(browser), true, null);`

Any idea to work with it? Thanks!

[https://github.com/rotorgames/Rg.Plugins.Popup](ref)

**Comment by didacvm** [comment]
I'm having the same issue.
Log output:
`Warning: Attempt to present <UINavigationController: 0x1124e0c00>  on <RgPopupPlatformRenderer: 0x1165511a0> which is already presenting <Rg_Plugins_Popup_IOS_Renderers_PopupPageRenderer: 0x1165489c0>`

And if I popup all RGPopups before:
`Warning: Attempt to present <UINavigationController: 0x1541fb800> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x153d909f0> whose view is not in the window hierarchy!`

**Comment by didacvm** [comment]
I actually solved it.
Plese refer to the pull request:
#22 
Thanks.

**Comment by nathan1658** [comment]
@didacvm 
Nice thanks for the quick solution!

**Comment by LeoJHarris** [comment]
@didacvm I saw this issue got merged. Is this working now? Can the issue be closed?

**Comment by didacvm** [comment]
@LeoJHarris Yes it's working, the issue can be closed.

**Comment by mimunoz** [comment]
Hi all, 
this change has been released in Nuget.org? I ask because I've the same issue and Nuget.org show this 
![image](https://user-images.githubusercontent.com/8498224/64054571-99880e00-cb55-11e9-9aef-de23b7348677.png)

Regards!
