### ISSUE TITLE
What version of Android are supported?

### ISSUE THREAD

**Issue by JimmyPun610** [stormlion227/PhotoBrowser.Forms#9]
I tried in Android 4.4 and 8.0.
It works fine in 4.4 but not in 8.0. The PhotoBrowser object always null.
Maybe due to the java lib?

**Comment by LeoJHarris** [comment]
![capture](https://user-images.githubusercontent.com/5468757/45518762-bc1afd00-b806-11e8-9722-f7da8d50c779.PNG)

Same issue here, null reference

**Comment by LeoJHarris** [comment]
I think this issue can be closed at it was to do with one of the libraries needing updating, nuget is working for me.

@JimmyPun610 was this issue resolved for you?

**Comment by JimmyPun610** [comment]
> I think this issue can be closed at it was to do with one of the libraries needing updating, nuget is working for me.
> 
> @JimmyPun610 was this issue resolved for you?

I avoid using this now. so I cannot test it.
Would you please share the updated library on nuget for me?

I am closing it now.
